# Generated by Django 4.1.2 on 2022-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10, unique=True)),
                ('atomic_unit', models.CharField(max_length=50)),
                ('base_unit', models.CharField(default=None, max_length=50)),
                ('description', models.TextField()),
                ('outgoing_tx_fee_amount', models.DecimalField(decimal_places=0, default=5000, max_digits=65)),
                ('blockheight', models.IntegerField(default=702398)),
                ('scan_started_at', models.DateTimeField(default=None, null=True)),
                ('blockchain_fee_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fee_account_asset', to='accounts.account')),
                ('custody_billing_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_billing_account', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='AssetAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_used_at', models.DateTimeField(default=None, null=True)),
                ('expired_at', models.DateTimeField(default=None, null=True)),
                ('received', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('address', models.CharField(db_index=True, default='', max_length=128, unique=True)),
                ('account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('confirmations', models.IntegerField(default=0)),
                ('tx_identifier', models.CharField(max_length=500, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.assetaddress')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('from_balance_before_tx', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('to_balance_before_tx', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('tx_type', models.IntegerField(choices=[(1, 'Deposit'), (2, 'Withdraw'), (3, 'Transfer'), (4, 'Internal Fee'), (5, 'Error Reversal')])),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset')),
                ('from_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='from_transactions', to='accounts.account')),
                ('incomingtx', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_transactions', to='accounts.incomingtransaction', verbose_name='Related incoming transaction')),
                ('to_account', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_transactions', to='accounts.account')),
                ('to_internal_address', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.assetaddress')),
            ],
        ),
        migrations.CreateModel(
            name='Outgoingtransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('broadcasted_at', models.DateTimeField(default=None, null=True)),
                ('canceled_at', models.DateTimeField(default=None, null=True)),
                ('to_address', models.TextField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=65)),
                ('transaction_base64', models.TextField(default=None, null=True)),
                ('txid', models.TextField(default=None, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset')),
                ('from_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('transaction', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='incomingtransaction',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.transaction'),
        ),
        migrations.AddField(
            model_name='account',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.asset'),
        ),
    ]
